export const rows = [
    {
      id: 1,
      img: "/assets/cards/1.png",
      Name: "Snow",
      status: 50,
      mh: 81,
      active:true,
      currentStatus:50,
      rarity: "legendary",
    },
    {
      id: 2,
      img: "/assets/cards/2.png",
      Name: "Lannister",
      status: 10,
      mh: 42,
      active:true,
      currentStatus:7,
      rarity: "common",
    },
    {
      id: 3,
      img: "/assets/cards/3.png",
      Name: "Lannister",
      status: 15,
      mh: 45,
      active:false,
      currentStatus:5,
      rarity: "epic",
    },
    {
      id: 4,
      img: "/assets/cards/4.png",
      Name: "Stark",
      status: 15,
      mh: 16,
      active:false,
      currentStatus:15,
      rarity: "uncommon",
    },
    {
      id: 5,
      img: "/assets/cards/5.png",
      Name: "Targaryen",
      status: 35,
      mh: null,
      active:false,
      currentStatus:10,
      rarity: "common",
    },
    {
      id: 6,
      img: "/assets/cards/6.png",
      Name: "Melisandre",
      status: 10,
      mh: 150,
      active:false,
      currentStatus:15,
      rarity: "uncommon",
    },
    {
      id: 7,
      img: "/assets/cards/7.png",
      Name: "Clifford",
      status: 10,
      mh: 44,
      active:false,
      currentStatus:5,
      rarity: "common",
    },
    {
      id: 8,
      img: "/assets/cards/8.png",
      Name: "Frances",
      status: 30,
      mh: 36,
      active:false,
      currentStatus:30,
      rarity: "common",
    },
    {
      id: 9,
      img: "/assets/cards/9.png",
      Name: "Roxie",
      status: 20,
      mh: 65,
      active:false,
      currentStatus:20,
      rarity: "legendary",
    },
    {
      id: 10,
      img: "/assets/cards/22.png",
      Name: "Targaryen",
      status: 25,
      mh: null,
      active:false,
      currentStatus:20,
      rarity: "common",
    },
    {
      id: 11,
      img: "/assets/cards/24.png",
      Name: "Melisandre",
      status: 20,
      mh: 150,
      active:false,
      currentStatus:20,
      rarity: "common",
    },
    {
      id: 12,
      img: "/assets/cards/27.png",
      Name: "Clifford",
      status: 20,
      mh: 44,
      active:true,
      currentStatus:20,
      rarity: "legendary",
    },
    {
      id: 13,
      img: "/assets/cards/28.png",
      Name: "Frances",
      status: 20,
      mh: 36,
      active:true,
      currentStatus:20,
      rarity: "epic",
    },
    {
      id: 14,
      img: "/assets/cards/29.png",
      Name: "Roxie",
      status: 20,
      mh: 65,
      active:true,
      currentStatus:20,
      rarity: "common",
    },
  ];
